/** GENERATED by scripts/generate-extraction-status.mjs — do not edit. */
export const extractionStatus = {
  "generatedAt": "2026-09-16T12:35:17.596Z",
  "shim": "make-server-37f42386",
  "fleetCoreScaffolded": true,
  "domains": {
    "fuel": {
      "slug": "fleet-fuel",
      "cutover": "done",
      "routeCount": 115
    },
    "toll": {
      "slug": "fleet-toll",
      "cutover": "done",
      "routeCount": 76
    },
    "ops": {
      "slug": "fleet-ops",
      "cutover": "done",
      "routeCount": 76
    },
    "claims": {
      "slug": "fleet-claims",
      "cutover": "done",
      "routeCount": 75
    },
    "pay": {
      "slug": "fleet-pay",
      "cutover": "done",
      "routeCount": 103
    }
  }
} as const;
