/** GENERATED by scripts/generate-extraction-status.mjs — do not edit. */
export const extractionStatus = {
  "shim": "make-server-37f42386",
  "fleetCoreScaffolded": true,
  "domains": {
    "fuel": {
      "slug": "fleet-fuel",
      "cutover": "done",
      "routeCount": 202
    },
    "toll": {
      "slug": "fleet-toll",
      "cutover": "done",
      "routeCount": 81
    },
    "ops": {
      "slug": "fleet-ops",
      "cutover": "done",
      "routeCount": 76
    },
    "claims": {
      "slug": "fleet-claims",
      "cutover": "done",
      "routeCount": 77
    },
    "pay": {
      "slug": "fleet-pay",
      "cutover": "done",
      "routeCount": 105
    }
  }
} as const;
