export {
  DEFAULT_REQUIRED_DOCS,
  RESTAURANT_GO_LIVE_RULE,
  REGULATED_VERTICALS,
  REGULATED_PERMIT_DOC,
  getVerticalPreset,
  applyVerticalPreset,
  normalizeRequiredDocumentTypes,
  getDefaultConfig,
  resolveVerticalType,
  resolveFulfillmentType,
  resolveGoLiveRule,
  isRegulatedVertical,
  getBusinessTypeConfig,
  getVerticalLabels,
  getCategoryTaxonomyKey,
  getCategoryTagsFromConfig,
  getComplianceTier,
  DOCUMENT_TYPE_LABELS,
} from './verticalConfig';
export type { VerticalLabels } from './verticalConfig';
