/** Manual QA matrix for cash settlement rollout (flag OFF vs ON). */
export const CASH_SETTLEMENT_QA = [
  'Flag OFF: cash trip on_trip → completed (legacy path)',
  'Flag OFF: card trip completes normally',
  'Flag OFF: Activity tab shows only completed/cancelled',
  'Flag OFF: wallet API unchanged / legacy transactions',
  'Flag OFF: earnings API and fleet sync unchanged',
  'Flag ON: cash trip → awaiting_cash_settlement → driver submits → completed',
  'Flag ON: rider on_trip does NOT show fare amount (cash badge only)',
  'Flag ON: rider sees locked fare only at awaiting_cash_settlement',
  'Flag ON: rider exact/overpay result on settlement screen before summary',
  'Flag ON: rider underpay/unpaid arrears on trip summary with Wallet link',
  'Flag ON: admin on_trip cash → Release to cash settlement (not generic Complete)',
  'Flag ON: admin awaiting_cash_settlement → Settle & complete with amount',
  'Flag ON: admin generic Complete blocked for cash (use_release_or_settle)',
  'Flag ON: driver Collect payment → mandatory cash entry overlay',
  'Flag ON: driver app relaunch routes to settlement screen',
  'Flag ON: exact / underpay / overpay / unpaid outcomes post correct journal',
  'Flag ON: driver blocked from new offers until settlement',
  'Flag ON: driver_net_minor unchanged when rider underpays',
  'Flag ON: ledger cash_collection line matches cash_received_minor',
  'Flag ON: idempotency replay 200; same key different amount 409',
  'Flag ON: wallet shows arrears_minor after underpay',
  'Flag ON: wallet shows credit_minor after overpay',
  'Flag ON: payment method sheet warns when arrears_minor > 0',
  'Flag ON: 7-day timeout auto-unpaid in staging (ops backstop only)',
] as const;
