/** Manual QA matrix for cash settlement rollout (flag OFF vs ON). */
export const CASH_SETTLEMENT_QA = [
  'Flag OFF: cash trip on_trip → completed (legacy path)',
  'Flag OFF: card trip completes normally',
  'Flag OFF: Activity tab shows only completed/cancelled',
  'Flag OFF: wallet API unchanged / legacy transactions',
  'Flag OFF: earnings API and fleet sync unchanged',
  'Flag ON: cash trip → awaiting_cash_settlement → driver submits → completed',
  'Flag ON: rider on_trip does NOT show fare amount (cash badge only)',
  'Flag ON: rider sees locked fare only at awaiting_cash_settlement',
  'Flag ON: rider exact/overpay result on settlement screen before summary',
  'Flag ON: rider underpay/unpaid arrears on trip summary with Wallet link',
  'Flag ON: admin on_trip cash → Release to cash settlement (not generic Complete)',
  'Flag ON: admin awaiting_cash_settlement → Settle & complete with amount',
  'Flag ON: admin generic Complete blocked for cash (use_release_or_settle)',
  'Flag ON: driver Collect payment → mandatory cash entry overlay',
  'Flag ON: driver app relaunch routes to settlement screen',
  'Flag ON: exact / underpay / overpay / unpaid outcomes post correct journal',
  'Flag ON: driver blocked from new offers until settlement',
  'Flag ON: driver_net_minor unchanged when rider underpays',
  'Flag ON: ledger cash_collection line matches cash_received_minor',
  'Flag ON: idempotency replay 200; same key different amount 409',
  'Flag ON: wallet shows arrears_minor after underpay',
  'Flag ON: wallet shows credit_minor after overpay',
  'Flag ON: payment method sheet warns when arrears_minor > 0',
  'Flag ON: 7-day timeout auto-unpaid in staging (ops backstop only)',
  'V2 OFF (V1 only): settlement posts to legacy user:{id}:driver account',
  'V2 ON: overpay credits driver:cash, rider change, digital debit or debt obligation',
  'V2 ON: GET /v1/drivers/me/wallets returns digital/cash/debt balances',
  'V2 ON: GET /v1/requests/:id/settlement-summary returns wallet_deltas snapshot',
  'V2 ON: rider CashTripSummaryView shows fare/cash/change/wallet balance',
  'V2 ON: driver post-settlement sheet shows wallet_deltas',
  'V2 ON: driver Trip wallets page lists per-wallet journal',
  'V2 ON: debt auto-repay on digital credit (FIFO obligations)',
  'V2 ON: admin wallet-reconciliation export lists cash vs open debt',
  'V2 ON: rollback — set CASH_SETTLEMENT_V2=0; V1 path resumes; snapshots read-only',
  'SPLIT ON: JMD 1,200 cash + wallet covers rest → outcome split, driver digital credited',
  'SPLIT ON: partial wallet + platform guarantee → rider_arrears_minor > 0, driver still paid',
  'SPLIT ON: driver complete view shows Trip paid — no "Rider owes"',
  'SPLIT ON: rider CashTripSummaryView shows cash + paid from wallet for split',
  'SPLIT ON: earnings digital_minor includes split wallet portion',
  'SPLIT ON: repair reclassifies legacy underpay trips with wallet journal to split',
  'SPLIT OFF: underpay path unchanged (no wallet_fare journal lines)',
  'SPLIT OFF: card trip completion unchanged',
] as const;

/** Staged rollout sequence (staging → production). */
export const CASH_SETTLEMENT_V2_ROLLOUT = [
  '1. Apply migrations 20260622120000 + 20260622130000 on staging',
  '2. Deploy rides edge; set CASH_SETTLEMENT_ENABLED=1 (V2 still off)',
  '3. Run V1 QA matrix; soak ≥ 48h',
  '4. Set CASH_SETTLEMENT_V2=1 + client VITE_CASH_SETTLEMENT_V2=1 on staging builds',
  '5. Run full V2 QA matrix including overpay with insufficient digital',
  '6. Apply migration 20260624120000_cash_split_settlement.sql (split outcome + journal types)',
  '7. Deploy rides edge; set CASH_SETTLEMENT_SPLIT_PAYMENT=1 on staging',
  '8. Run SPLIT QA matrix (exact, overpay, split full/partial wallet, card, flag OFF regression)',
  '9. Run historical repair on staging underpay trips with wallet journal evidence',
  '10. Production: repeat steps 6–9; monitor journal idempotency conflicts',
  '11. Rollback split: CASH_SETTLEMENT_SPLIT_PAYMENT=0 — legacy underpay path resumes',
  '12. Rollback V2: CASH_SETTLEMENT_V2=0 (server + client); V1 journal path resumes immediately',
  '13. Optional: enable CASH_SETTLEMENT_DEBT_DISPATCH_GUARD=1 after ≥2 week soak',
] as const;
