/** Default profile avatar for home header when user has no photo. */
export const DEFAULT_PROFILE_AVATAR_URL =
  'https://lh3.googleusercontent.com/aida-public/AB6AXuBHAFPNamxsbipRMwXCtHZzwZSnhXnqMnPEQll9hnYxM_fLaYbULFNNuo_6QkZDgpNbgHqcn0D8-TguO--3Pa30qku7VS0xQEyzBfCoXF2xztqQOFSr93hV4ReKr4TkYIOHjZYnrrJo-vDeZ5NCpG0Vh0FjCgpVqWblWNa7XwYGqhAIwaiRvsHMEuynUTiuHe5NPplG3QShkqrY7a-RP-PJlgtvDn7qJf0eq3T9932h5tdJSVX6_Rmze8zuHdHmrHoXbqRoxh_u0Wh2';
