// =============================================================================
// Toll Plaza Type Definitions
// =============================================================================
// Data model for the Toll Database feature (mirrors station.ts for fuel).
// KV key pattern: toll_plaza:{id}
// =============================================================================

// --- Step 1.1: Plaza verification status ---
export type TollPlazaStatus = 'verified' | 'unverified' | 'learnt';

// --- Step 1.2: Travel direction the plaza services ---
export type TollDirection =
  | 'Eastbound'
  | 'Westbound'
  | 'Northbound'
  | 'Southbound'
  | 'Both'
  | 'Unknown';

// --- Step 1.3: Toll plaza operator / concessionaire ---
export type TollOperator =
  | 'TransJamaican Highway'
  | 'NROCC'
  | 'Other';

// --- Step 1.4: Jamaica Highway vehicle classification ---
export type TollVehicleClass =
  | 'Class 1'
  | 'Class 2'
  | 'Class 3'
  | 'Class 4'
  | 'Class 5';

// --- Step 1.5: Per-class toll rate ---
export interface TollRate {
  vehicleClass: TollVehicleClass;
  rate: number;            // Amount in JMD
  currency: string;        // Default 'JMD'
  effectiveDate: string;   // ISO date — when this rate took effect
}

// --- Step 1.6: Aggregated statistics for a plaza ---
export interface TollPlazaStats {
  totalTransactions: number;
  totalSpend: number;          // Sum of all toll amounts at this plaza (JMD)
  lastTransactionDate: string; // ISO date
  avgAmount: number;           // Average toll amount per transaction
  lastUpdated: string;         // ISO date — last time stats were recalculated
}

// --- Step 1.7: Main toll plaza entity ---
export interface TollPlaza {
  id: string;                      // Unique ID (UUID generated by backend)
  name: string;                    // e.g. "Portmore Toll Plaza"
  highway: string;                 // e.g. "Highway 2000 (East-West)"
  direction: TollDirection;
  operator: TollOperator | string; // Union allows free-text for custom operators

  // GPS & spatial
  location: {
    lat: number;
    lng: number;
    accuracy?: number;             // GPS accuracy in meters (if available)
  };
  plusCode?: string;                // Google Plus Code for high-precision matching
  geofenceRadius?: number;         // Meters — matching radius for spatial audit

  // Address
  address?: string;
  parish?: string;                 // Jamaican administrative division (e.g. "St. Catherine")

  // Toll rates by vehicle class
  rates?: TollRate[];

  // Status & metadata
  status: TollPlazaStatus;
  operationalStatus?: 'active' | 'inactive' | 'under_construction';
  dataSource: 'manual' | 'import' | 'learnt';

  // Aggregated statistics
  stats: TollPlazaStats;

  // Optional info
  notes?: string;
  contactInfo?: {
    phone?: string;
    website?: string;
  };

  // Timestamps
  createdAt: string;               // ISO date
  updatedAt: string;               // ISO date
}
