/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_37f42386 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/csfllzzastacofsvcdsc/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

const client = () => createClient(
  Deno.env.get("SUPABASE_URL"),
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),
);

/** PostgREST default max rows is 1000 — must page or trips/fuel silently truncate. */
const KV_PAGE_SIZE = 1000;

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_37f42386").upsert({
    key,
    value
  });
  if (error) {
    throw new Error(error.message);
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_37f42386").select("value").eq("key", key).maybeSingle();
  if (error) {
    throw new Error(error.message);
  }
  return data?.value;
};

// Delete deletes a key-value pair in the database.
export const del = async (key: string): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_37f42386").delete().eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_37f42386").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) {
    throw new Error(error.message);
  }
};

// Gets multiple key-value pairs in the database.
// Results are returned in the same order as `keys` (Postgres IN does not guarantee order).
export const mget = async (keys: string[]): Promise<any[]> => {
  if (keys.length === 0) return [];
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_37f42386").select("key, value").in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
  const byKey = new Map((data ?? []).map((row) => [row.key, row.value]));
  return keys.map((k) => byKey.get(k) ?? null);
};

// Deletes multiple key-value pairs in the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_37f42386").delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

/**
 * Search for key-value pairs by prefix.
 * Pages through all matches — never return a silent 1000-row slice.
 */
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const supabase = client();
  const out: any[] = [];
  let from = 0;
  for (;;) {
    const { data, error } = await supabase
      .from("kv_store_37f42386")
      .select("key, value")
      .like("key", prefix + "%")
      .order("key", { ascending: true })
      .range(from, from + KV_PAGE_SIZE - 1);
    if (error) {
      throw new Error(error.message);
    }
    const rows = data ?? [];
    for (const row of rows) out.push(row.value);
    if (rows.length < KV_PAGE_SIZE) break;
    from += KV_PAGE_SIZE;
  }
  return out;
};
